# Generated by Django 4.2.1 on 2023-05-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderpickup',
            name='email',
        ),
    ]
