# Generated by Django 3.2.19 on 2023-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_remove_order_email_remove_orderpickup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpickup',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
